server:
  port: 8081
user-service:
  url: http://localhost:8080
load:
  threads: 100
  createRequests: 100000
  readRequests: 1000000
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
logging:
  level:
    ru.ageeva.loadtestservice: ERROR
    org.springframework.web.client: ERROR